Repository obsidian-community/obsidian-hub, pull requests merged in 2021-12, with the labels that each got.

#130 minor fixes/changes in the stylelint guide based on some feedback
  04 - Guides, Workflows, & Courses/Guides/Why and How to use Stylelint for your Obsidian Theme.md
Labels: < 5 lines change

#131 Added Concept note: Sherlocking
  05 - Concepts/Sherlocking.md
Labels: new content

#133 Categorize "Reveal Active File Button" plugin
  02 - Community Expansions/02.01 Plugins by Category/Plugins to navigate notes.md
  02 - Community Expansions/02.01 Plugins by Category/Uncategorized plugins.md
Labels: < 5 lines change

#134 Added reminder to link newly created notes
  .github/pull_request_template.md
Labels: < 5 lines change

#170 Added Link to the Composite Vault Guide by @tzhouhc
  04 - Guides, Workflows, & Courses/for Power Users.md
Labels: < 5 lines change

#176 Split plugin and theme templates into smaller modular templates
  .github/scripts/templates/funding.md.jinja
  .github/scripts/templates/plugin.md.jinja
  .github/scripts/templates/plugins/badges.md.jinja
  .github/scripts/templates/plugins/frontmatter.md.jinja
  .github/scripts/templates/plugins/plugin_info.md.jinja
  .github/scripts/templates/theme.md.jinja
  .github/scripts/templates/themes/badges.md.jinja
  .github/scripts/templates/themes/frontmatter.md.jinja
  .github/scripts/templates/themes/plugin_compatibility.md.jinja
  .github/scripts/templates/themes/style_settings.md.jinja
  .github/scripts/templates/themes/theme_info.md.jinja
Labels: hub tools & scripts

#178 Add new themes and plugins for W52
  01 - Community/People/Gru80.md
  01 - Community/People/Thiews.md
  01 - Community/People/devbean.md
  01 - Community/People/dlccyes.md
  01 - Community/People/dracula.md
  01 - Community/People/getmatterapp.md
  02 - Community Expansions/02.01 Plugins by Category/Uncategorized plugins.md
  02 - Community Expansions/02.05 All Community Expansions/Plugins/linked-data-helper.md
  02 - Community Expansions/02.05 All Community Expansions/Plugins/linked-data-vocabularies.md
  02 - Community Expansions/02.05 All Community Expansions/Plugins/matter.md
  02 - Community Expansions/02.05 All Community Expansions/Plugins/obsidian-icon-shortcodes.md
  02 - Community Expansions/02.05 All Community Expansions/Plugins/obsidian-regex-replace.md
  02 - Community Expansions/02.05 All Community Expansions/Plugins/obsidian-wordpress.md
  02 - Community Expansions/02.05 All Community Expansions/Themes/Dracula Official.md
  02 - Community Expansions/02.05 All Community Expansions/Themes/Harmonic.md
  02 - Community Expansions/02.05 All Community Expansions/Themes/Nebula.md
Labels: scripted update

#184 Fix dangling link to note called Overdue
  01 - Community/Obsidian Roundup/2021-11-27  Rearrange Outlines and Integrate your Content Discovery Process.md
Labels: < 5 lines change

#189 add link to a guide
  04 - Guides, Workflows, & Courses/for Creative Writing.md
Labels: < 5 lines change
