Repository obsidian-community/obsidian-hub, pull requests merged in 2022-01, with the labels that each got.

#196 Update extensions
  01 - Community/People/QAMichaelPeng.md
  01 - Community/People/aidanglickman.md
  01 - Community/People/🗂️ People.md
  02 - Community Expansions/02.01 Plugins by Category/Uncategorized plugins.md
  02 - Community Expansions/02.05 All Community Expansions/Plugins/obsidian-advanced-slides.md
  02 - Community Expansions/02.05 All Community Expansions/Plugins/obsidian-graphviz.md
  02 - Community Expansions/02.05 All Community Expansions/Plugins/obsidian-tagfolder.md
  02 - Community Expansions/02.05 All Community Expansions/Plugins/🗂️ Plugins.md
  02 - Community Expansions/02.05 All Community Expansions/Themes/Obsidian Nord Enhanced.md
  02 - Community Expansions/02.05 All Community Expansions/Themes/🗂️ Themes.md
  04 - Guides, Workflows, & Courses/🗂️ 04 - Guides, Workflows, & Courses.md
Labels: scripted update

#199 add link to template theme
  04 - Guides, Workflows, & Courses/for Theme Designers.md
Labels: < 5 lines change

#200 added link for people management + fixed LYT link
  04 - Guides, Workflows, & Courses/for Knowledge Management.md
Labels: < 5 lines change

#212 add css to two code blocks in css guide
  04 - Guides, Workflows, & Courses/Guides/How to Style Obsidian.md
Labels: < 5 lines change

#214 Update 🗂️ Vaults.md
  03 - Showcases & Templates/Vaults/🗂️ Vaults.md
Labels: < 5 lines change

#225 Add missing closing parentheses on 3 external links
  01 - Community/Obsidian Roundup/2021.06.19.md
  01 - Community/Obsidian Roundup/2021.08.14.md
  01 - Community/Obsidian Roundup/2021.08.21.md
Labels: < 5 lines change

#223 Fix 2 wiki links
  01 - Community/Obsidian Roundup/2021.08.21.md
  04 - Guides, Workflows, & Courses/Community Talks/Breadcrumbs Showcase.md
Labels: < 5 lines change

#228 Add tests for add_footer.py - and fix 'Edit In GitHub' & 'Copy this note' links
  .github/scripts/add_footer.py
  .github/scripts/templates/footer.md.jinja
  .github/scripts/tests/approved_files/test_add_footer.test_footer_added_if_missing.approved.md
  .github/scripts/tests/approved_files/test_add_footer.test_footer_updated_if_present.approved.md
  .github/scripts/tests/test_add_footer.py
Labels: hub tools & scripts

#242 Add footers for the files in root of the vault
  00 - Start here.md
  CONTRIBUTING.md
  README.md
  🗂️ hub.md
Labels: scripted update

#241 Add footers for '06 - Inbox'
  06 - Inbox/Backlinks Panel HTML Svelte Component.md
  06 - Inbox/ClubMacStories.md
  06 - Inbox/Customer Relationship Management.md
  06 - Inbox/HAProxy.md
  06 - Inbox/LYT House.md
  06 - Inbox/Let's Encrypt.md
  06 - Inbox/Nomic.md
  06 - Inbox/Obsidian CSS.md
  06 - Inbox/Obsidian Flight School.md
  06 - Inbox/Productivity Guru.md
  06 - Inbox/Seedbox.md
  06 - Inbox/SkillShare.md
  06 - Inbox/Yet Another Free Publish Alternative.md
  06 - Inbox/pfSense.md
  06 - Inbox/🗂️ 06 - Inbox.md
Labels: scripted update

#240 Add footers for '05 - Concepts'
  05 - Concepts/A Brief History and Ethos of the Digital Garden.md
  05 - Concepts/Buy me a coffee.md
  05 - Concepts/Digital garden.md
  05 - Concepts/GitHub sponsors.md
  05 - Concepts/HTML.md
  05 - Concepts/Knowledge Management System.md
  05 - Concepts/LaTeX.md
  05 - Concepts/Maps of Content (MOC).md
  05 - Concepts/Markdown.md
  05 - Concepts/Mermaid.md
  05 - Concepts/Obsidian Core Plugins.md
  05 - Concepts/Obsidian Help.md
  05 - Concepts/Obsidian Publish.md
  05 - Concepts/Obsidian Sync.md
  05 - Concepts/Obsidian community plugins.md
  05 - Concepts/Obsidian community themes.md
  05 - Concepts/Obsidian queries.md
  05 - Concepts/Obsidian.md
  05 - Concepts/PARA.md
  05 - Concepts/Patreon.md
  05 - Concepts/PayPal.md
  05 - Concepts/Publish sites.md
  05 - Concepts/SCSS.md
  05 - Concepts/Sherlocking.md
  05 - Concepts/Spaced repetition.md
  05 - Concepts/Websites.md
  05 - Concepts/YAML frontmatter.md
  05 - Concepts/Zettelkasten.md
  05 - Concepts/🗂️ 05 - Concepts.md
Labels: scripted update

#238 Add footers for '03 - Showcases & Templates'
  03 - Showcases & Templates/Dashboards/Wordcount Dashboard.md
  03 - Showcases & Templates/Dashboards/🗂️ Dashboards.md
  03 - Showcases & Templates/Note Examples/🗂️ Note Examples.md
  03 - Showcases & Templates/Plugin Showcases/Breadcrumbs for Comparative Law.md
  03 - Showcases & Templates/Plugin Showcases/Graph view.md
  03 - Showcases & Templates/Plugin Showcases/Obsidian-Dice-Roller-Tables-Collection.md
  03 - Showcases & Templates/Plugin Showcases/Tooltips for Literature Notes with Supercharged Links.md
  03 - Showcases & Templates/Plugin Showcases/🗂️ Plugin Showcases.md
  03 - Showcases & Templates/Publish Sites/Obsidian Garden.md
  03 - Showcases & Templates/Publish Sites/🗂️ Publish Sites.md
  03 - Showcases & Templates/Templates/Daily notes/T - Thecookiemomma's Daily Log.md
  03 - Showcases & Templates/Templates/Daily notes/🗂️ Daily notes.md
  03 - Showcases & Templates/Templates/Literature notes/🗂️ Literature notes.md
  03 - Showcases & Templates/Templates/Monthly notes/🗂️ Monthly notes.md
  03 - Showcases & Templates/Templates/Plugin-specific templates/Dataview templates/Locale Dataview Query Template.md
  03 - Showcases & Templates/Templates/Plugin-specific templates/Dataview templates/Project Cards.md
  03 - Showcases & Templates/Templates/Plugin-specific templates/Dataview templates/🗂️ Dataview templates.md
  03 - Showcases & Templates/Templates/Plugin-specific templates/Templater templates/🗂️ Templater templates.md
  03 - Showcases & Templates/Templates/Plugin-specific templates/🗂️ Plugin-specific templates.md
  03 - Showcases & Templates/Templates/Projects/🗂️ Projects.md
  03 - Showcases & Templates/Templates/TTRPG notes/Button Action & Trait Templates.md
  03 - Showcases & Templates/Templates/TTRPG notes/DnD Character Sheet.md
  03 - Showcases & Templates/Templates/TTRPG notes/Locale Template.md
  03 - Showcases & Templates/Templates/TTRPG notes/🗂️ TTRPG notes.md
  03 - Showcases & Templates/Templates/Weekly notes/🗂️ Weekly notes.md
  03 - Showcases & Templates/Templates/Yearly notes/🗂️ Yearly notes.md
  03 - Showcases & Templates/Templates/🗂️ Templates.md
  03 - Showcases & Templates/Vaults/LYT Kit.md
  03 - Showcases & Templates/Vaults/Life Disciplines Projects.md
  03 - Showcases & Templates/Vaults/OB_Template.md
  03 - Showcases & Templates/Vaults/Obsidian JG Method.md
  03 - Showcases & Templates/Vaults/Obsidian Starter Templates.md
  03 - Showcases & Templates/Vaults/PARA Starter Kit.md
  03 - Showcases & Templates/Vaults/Qualitative Analysis Environment by Ryan Murphy.md
  03 - Showcases & Templates/Vaults/SlRvb's Journaling Setup.md
  03 - Showcases & Templates/Vaults/SlRvb's MediaDB Setup.md
  03 - Showcases & Templates/Vaults/🗂️ Vaults.md
  03 - Showcases & Templates/🗂️ 03 - Showcases & Templates.md
Labels: scripted update

#234 Add footers for '00 - Contribute to the Obsidian Hub/'
  00 - Contribute to the Obsidian Hub/02 Attachments/🗂️ 02 Attachments.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.01 Structure/Checklist for reviewing Pull Requests.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.01 Structure/🗂️ 03.01 Structure.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.02 Design Decisions/Content Comments.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.02 Design Decisions/Content Lifecycle of Extensions.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.02 Design Decisions/Content Lists.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.02 Design Decisions/Content People.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.02 Design Decisions/Content Plugins.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.02 Design Decisions/Content Themes.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.02 Design Decisions/🗂️ 03.02 Design Decisions.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.03 Scripts and Automation/Checking Hub Content.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.03 Scripts and Automation/GitHub Actions for the Hub.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.03 Scripts and Automation/Scripts for Maintenance.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.03 Scripts and Automation/Testing Python Code with Approval Tests.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.03 Scripts and Automation/Updating Extensions.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.03 Scripts and Automation/Updating MOC files.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/03.03 Scripts and Automation/🗂️ 03.03 Scripts and Automation.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/Discussion Needed.md
  00 - Contribute to the Obsidian Hub/03 Contributor Notes/🗂️ 03 Contributor Notes.md
  00 - Contribute to the Obsidian Hub/Contributing templates to the community vault.md
  00 - Contribute to the Obsidian Hub/Contributing with community plugins and themes.md
  00 - Contribute to the Obsidian Hub/FAQ.md
  00 - Contribute to the Obsidian Hub/Obsidian Settings for Contributors.md
  00 - Contribute to the Obsidian Hub/Tag glossary.md
  00 - Contribute to the Obsidian Hub/Tip for Keeping Hub TODO lists.md
  00 - Contribute to the Obsidian Hub/🗂️ 00 - Contribute to the Obsidian Hub.md
Labels: scripted update

#253 Update for Creative Writing.md
  04 - Guides, Workflows, & Courses/for Creative Writing.md
Labels: < 5 lines change

#252 Update for Academic Writing.md
  04 - Guides, Workflows, & Courses/for Academic Writing.md
Labels: < 5 lines change

#269 added one link for Theme Designers.md
  04 - Guides, Workflows, & Courses/for Theme Designers.md
Labels: < 5 lines change
